schedules:
- cron: "0 3 * * Mon"
  displayName: Weekly build
  branches:
    include:
    - master

jobs:
- job: 'ParallelTesting'
  pool:
    vmImage: 'ubuntu-latest'
  displayName: Run tests in parallel

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 5.0.x'
    inputs:
      packageType: sdk
      version: 5.0.x

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.csproj'

  - bash: |
      tests=($(dotnet test . --no-build --list-tests | grep Test_))
      . 'create_slicing_filter_condition.sh' $tests
    displayName: 'Create slicing filter condition'
  
  - bash: |
      echo "Slicing filter condition: $(targetTestsFilter)"
    displayName: 'Echo slicing filter condition'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/*Tests/*Tests.csproj'
      arguments: '--no-restore --output $(Build.SourcesDirectory)/out'
      zipAfterPublish: false
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*Tests/*Tests.csproj'
      arguments: '--filter "$(targetTestsFilter)"'